#include "symbols.hpp"

namespace erdflow::desktop {

const std::vector<SymbolGroup>& symbol_groups() {
    // Built once and handed out by reference; the table is fixed, and the
    // picker rebuilds its grid from it on every search.
    static const std::vector<SymbolGroup> groups = [] {
        std::vector<SymbolGroup> all;
        all.push_back({QStringLiteral("Relational algebra"),
                       {{QStringLiteral("σ"), QStringLiteral("sigma, select, restriction")},
                        {QStringLiteral("π"), QStringLiteral("pi, project, projection")},
                        {QStringLiteral("ρ"), QStringLiteral("rho, rename")},
                        {QStringLiteral("⋈"), QStringLiteral("natural join, bowtie")},
                        {QStringLiteral("⟕"), QStringLiteral("left outer join")},
                        {QStringLiteral("⟖"), QStringLiteral("right outer join")},
                        {QStringLiteral("⟗"), QStringLiteral("full outer join")},
                        {QStringLiteral("⋉"), QStringLiteral("left semijoin")},
                        {QStringLiteral("⋊"), QStringLiteral("right semijoin")},
                        {QStringLiteral("▷"), QStringLiteral("antijoin")},
                        {QStringLiteral("∪"), QStringLiteral("union")},
                        {QStringLiteral("∩"), QStringLiteral("intersection")},
                        {QStringLiteral("−"), QStringLiteral("difference, minus")},
                        {QStringLiteral("×"), QStringLiteral("cartesian product, times, cross")},
                        {QStringLiteral("÷"), QStringLiteral("division, divide")},
                        {QStringLiteral("←"), QStringLiteral("assignment, gets")},
                        {QStringLiteral("γ"), QStringLiteral("gamma, grouping, aggregation")},
                        {QStringLiteral("τ"), QStringLiteral("tau, sort, order by")},
                        {QStringLiteral("δ"), QStringLiteral("delta, duplicate removal, distinct")}}});
        all.push_back({QStringLiteral("Logic and sets"),
                       {{QStringLiteral("∧"), QStringLiteral("and, conjunction")},
                        {QStringLiteral("∨"), QStringLiteral("or, disjunction")},
                        {QStringLiteral("¬"), QStringLiteral("not, negation")},
                        {QStringLiteral("⊕"), QStringLiteral("exclusive or, xor, disjoint")},
                        {QStringLiteral("∀"), QStringLiteral("for all, universal")},
                        {QStringLiteral("∃"), QStringLiteral("there exists, existential")},
                        {QStringLiteral("∄"), QStringLiteral("there does not exist")},
                        {QStringLiteral("∈"), QStringLiteral("element of, member of, belongs to")},
                        {QStringLiteral("∉"), QStringLiteral("not an element of")},
                        {QStringLiteral("⊆"), QStringLiteral("subset of or equal to, total")},
                        {QStringLiteral("⊂"), QStringLiteral("proper subset of")},
                        {QStringLiteral("⊇"), QStringLiteral("superset of or equal to")},
                        {QStringLiteral("⊃"), QStringLiteral("proper superset of")},
                        {QStringLiteral("∅"), QStringLiteral("empty set, null")},
                        {QStringLiteral("≡"), QStringLiteral("identical to, equivalent")},
                        {QStringLiteral("≠"), QStringLiteral("not equal to")},
                        {QStringLiteral("≤"), QStringLiteral("less than or equal to")},
                        {QStringLiteral("≥"), QStringLiteral("greater than or equal to")},
                        {QStringLiteral("⊤"), QStringLiteral("true, top")},
                        {QStringLiteral("⊥"), QStringLiteral("false, bottom, perpendicular")}}});
        all.push_back({QStringLiteral("Arrows"),
                       {{QStringLiteral("→"), QStringLiteral("right arrow, determines, functional dependency")},
                        {QStringLiteral("←"), QStringLiteral("left arrow")},
                        {QStringLiteral("↑"), QStringLiteral("up arrow")},
                        {QStringLiteral("↓"), QStringLiteral("down arrow")},
                        {QStringLiteral("↔"), QStringLiteral("left right arrow, both ways")},
                        {QStringLiteral("↕"), QStringLiteral("up down arrow")},
                        {QStringLiteral("⇒"), QStringLiteral("implies, double right arrow")},
                        {QStringLiteral("⇐"), QStringLiteral("double left arrow")},
                        {QStringLiteral("⇔"), QStringLiteral("if and only if, double both ways")},
                        {QStringLiteral("↠"), QStringLiteral("multivalued dependency, two headed arrow")},
                        {QStringLiteral("↦"), QStringLiteral("maps to")},
                        {QStringLiteral("⇄"), QStringLiteral("both directions, exchange")},
                        {QStringLiteral("↪"), QStringLiteral("hooks right, inclusion")},
                        {QStringLiteral("↩"), QStringLiteral("hooks left")},
                        {QStringLiteral("⤴"), QStringLiteral("arrow curving up")},
                        {QStringLiteral("⤵"), QStringLiteral("arrow curving down")}}});
        all.push_back({QStringLiteral("Mathematics"),
                       {{QStringLiteral("±"), QStringLiteral("plus minus")},
                        {QStringLiteral("≈"), QStringLiteral("approximately equal to")},
                        {QStringLiteral("∞"), QStringLiteral("infinity")},
                        {QStringLiteral("√"), QStringLiteral("square root")},
                        {QStringLiteral("∑"), QStringLiteral("sum, summation")},
                        {QStringLiteral("∏"), QStringLiteral("product")},
                        {QStringLiteral("∫"), QStringLiteral("integral")},
                        {QStringLiteral("∂"), QStringLiteral("partial derivative")},
                        {QStringLiteral("∆"), QStringLiteral("delta, change")},
                        {QStringLiteral("∇"), QStringLiteral("nabla, gradient")},
                        {QStringLiteral("°"), QStringLiteral("degree")},
                        {QStringLiteral("‰"), QStringLiteral("per mille")},
                        {QStringLiteral("∝"), QStringLiteral("proportional to")},
                        {QStringLiteral("∠"), QStringLiteral("angle")},
                        {QStringLiteral("∥"), QStringLiteral("parallel to")},
                        {QStringLiteral("⌈"), QStringLiteral("left ceiling")},
                        {QStringLiteral("⌉"), QStringLiteral("right ceiling")},
                        {QStringLiteral("⌊"), QStringLiteral("left floor")},
                        {QStringLiteral("⌋"), QStringLiteral("right floor")}}});
        all.push_back({QStringLiteral("Greek letters"),
                       {{QStringLiteral("α"), QStringLiteral("alpha")},
                        {QStringLiteral("β"), QStringLiteral("beta")},
                        {QStringLiteral("γ"), QStringLiteral("gamma")},
                        {QStringLiteral("δ"), QStringLiteral("delta")},
                        {QStringLiteral("ε"), QStringLiteral("epsilon")},
                        {QStringLiteral("ζ"), QStringLiteral("zeta")},
                        {QStringLiteral("η"), QStringLiteral("eta")},
                        {QStringLiteral("θ"), QStringLiteral("theta, theta join")},
                        {QStringLiteral("κ"), QStringLiteral("kappa")},
                        {QStringLiteral("λ"), QStringLiteral("lambda")},
                        {QStringLiteral("μ"), QStringLiteral("mu")},
                        {QStringLiteral("ν"), QStringLiteral("nu")},
                        {QStringLiteral("ξ"), QStringLiteral("xi")},
                        {QStringLiteral("π"), QStringLiteral("pi")},
                        {QStringLiteral("ρ"), QStringLiteral("rho")},
                        {QStringLiteral("σ"), QStringLiteral("sigma")},
                        {QStringLiteral("τ"), QStringLiteral("tau")},
                        {QStringLiteral("φ"), QStringLiteral("phi")},
                        {QStringLiteral("χ"), QStringLiteral("chi")},
                        {QStringLiteral("ψ"), QStringLiteral("psi")},
                        {QStringLiteral("ω"), QStringLiteral("omega")},
                        {QStringLiteral("Γ"), QStringLiteral("capital gamma")},
                        {QStringLiteral("Δ"), QStringLiteral("capital delta")},
                        {QStringLiteral("Θ"), QStringLiteral("capital theta")},
                        {QStringLiteral("Λ"), QStringLiteral("capital lambda")},
                        {QStringLiteral("Ξ"), QStringLiteral("capital xi")},
                        {QStringLiteral("Π"), QStringLiteral("capital pi")},
                        {QStringLiteral("Σ"), QStringLiteral("capital sigma")},
                        {QStringLiteral("Φ"), QStringLiteral("capital phi")},
                        {QStringLiteral("Ψ"), QStringLiteral("capital psi")},
                        {QStringLiteral("Ω"), QStringLiteral("capital omega")}}});
        all.push_back({QStringLiteral("Punctuation and marks"),
                       {{QStringLiteral("•"), QStringLiteral("bullet")},
                        {QStringLiteral("‣"), QStringLiteral("triangular bullet")},
                        {QStringLiteral("–"), QStringLiteral("en dash")},
                        {QStringLiteral("—"), QStringLiteral("em dash")},
                        {QStringLiteral("…"), QStringLiteral("ellipsis, and so on")},
                        {QStringLiteral("«"), QStringLiteral("left guillemet, stereotype")},
                        {QStringLiteral("»"), QStringLiteral("right guillemet, stereotype")},
                        {QStringLiteral("“"), QStringLiteral("left double quote")},
                        {QStringLiteral("”"), QStringLiteral("right double quote")},
                        {QStringLiteral("‘"), QStringLiteral("left single quote")},
                        {QStringLiteral("’"), QStringLiteral("right single quote, apostrophe")},
                        {QStringLiteral("§"), QStringLiteral("section")},
                        {QStringLiteral("¶"), QStringLiteral("paragraph, pilcrow")},
                        {QStringLiteral("†"), QStringLiteral("dagger, footnote")},
                        {QStringLiteral("‡"), QStringLiteral("double dagger")},
                        {QStringLiteral("©"), QStringLiteral("copyright")},
                        {QStringLiteral("®"), QStringLiteral("registered")},
                        {QStringLiteral("™"), QStringLiteral("trademark")},
                        {QStringLiteral("№"), QStringLiteral("numero, number")},
                        {QStringLiteral("✓"), QStringLiteral("check, tick, yes, done")},
                        {QStringLiteral("✗"), QStringLiteral("cross, no, not done")},
                        {QStringLiteral("★"), QStringLiteral("filled star")},
                        {QStringLiteral("☆"), QStringLiteral("open star")},
                        {QStringLiteral("▪"), QStringLiteral("small square")},
                        {QStringLiteral("♦"), QStringLiteral("diamond")},
                        {QStringLiteral("⚑"), QStringLiteral("flag")},
                        {QStringLiteral("⌘"), QStringLiteral("command key")},
                        {QStringLiteral("⌥"), QStringLiteral("option key, alt")},
                        {QStringLiteral("⇧"), QStringLiteral("shift key")},
                        {QStringLiteral("⏎"), QStringLiteral("return key, enter")}}});
        all.push_back({QStringLiteral("Emoji"),
                       {{QStringLiteral("🙂"), QStringLiteral("slightly smiling face, happy")},
                        {QStringLiteral("😐"), QStringLiteral("neutral face")},
                        {QStringLiteral("🙁"), QStringLiteral("slightly frowning face, sad")},
                        {QStringLiteral("👍"), QStringLiteral("thumbs up, approved, yes")},
                        {QStringLiteral("👎"), QStringLiteral("thumbs down, rejected, no")},
                        {QStringLiteral("✅"), QStringLiteral("check mark button, done, agreed")},
                        {QStringLiteral("❌"), QStringLiteral("cross mark, wrong, removed")},
                        {QStringLiteral("⚠️"), QStringLiteral("warning, careful")},
                        {QStringLiteral("❗"), QStringLiteral("exclamation mark, important")},
                        {QStringLiteral("❓"), QStringLiteral("question mark, unresolved, ask")},
                        {QStringLiteral("💡"), QStringLiteral("light bulb, idea, suggestion")},
                        {QStringLiteral("📌"), QStringLiteral("pushpin, pinned, note")},
                        {QStringLiteral("📎"), QStringLiteral("paperclip, attachment")},
                        {QStringLiteral("🔑"), QStringLiteral("key, primary key")},
                        {QStringLiteral("🗝️"), QStringLiteral("old key, foreign key")},
                        {QStringLiteral("🔒"), QStringLiteral("locked, fixed")},
                        {QStringLiteral("🔓"), QStringLiteral("unlocked, open")},
                        {QStringLiteral("📁"), QStringLiteral("folder, group")},
                        {QStringLiteral("📄"), QStringLiteral("page, document, record")},
                        {QStringLiteral("📊"), QStringLiteral("bar chart, report")},
                        {QStringLiteral("🗄️"), QStringLiteral("file cabinet, database, store")},
                        {QStringLiteral("🧩"), QStringLiteral("puzzle piece, part of")},
                        {QStringLiteral("⏱️"), QStringLiteral("stopwatch, timing, performance")},
                        {QStringLiteral("🔍"), QStringLiteral("magnifying glass, search, look at")},
                        {QStringLiteral("⭐"), QStringLiteral("star, favourite")},
                        {QStringLiteral("🚩"), QStringLiteral("triangular flag, flagged, problem")},
                        {QStringLiteral("🐛"), QStringLiteral("bug, defect")},
                        {QStringLiteral("🔥"), QStringLiteral("fire, urgent, hot")},
                        {QStringLiteral("✨"), QStringLiteral("sparkles, new")},
                        {QStringLiteral("🚧"), QStringLiteral("construction, work in progress")},
                        {QStringLiteral("😀"), QStringLiteral("grinning face, happy")},
                        {QStringLiteral("😄"), QStringLiteral("smiling face, glad")},
                        {QStringLiteral("😉"), QStringLiteral("winking face")},
                        {QStringLiteral("😍"), QStringLiteral("heart eyes, love")},
                        {QStringLiteral("🤔"), QStringLiteral("thinking face, unsure")},
                        {QStringLiteral("😮"), QStringLiteral("surprised face")},
                        {QStringLiteral("😢"), QStringLiteral("crying face, sad")},
                        {QStringLiteral("😡"), QStringLiteral("angry face")},
                        {QStringLiteral("😴"), QStringLiteral("sleeping face, idle")},
                        {QStringLiteral("🤝"), QStringLiteral("handshake, agreement")},
                        {QStringLiteral("👋"), QStringLiteral("waving hand, hello")},
                        {QStringLiteral("👀"), QStringLiteral("eyes, look at this")},
                        {QStringLiteral("🙌"), QStringLiteral("raised hands, celebration")},
                        {QStringLiteral("💪"), QStringLiteral("flexed arm, strong")},
                        {QStringLiteral("🧠"), QStringLiteral("brain, logic")},
                        {QStringLiteral("✔️"), QStringLiteral("heavy check mark, done")},
                        {QStringLiteral("✖️"), QStringLiteral("heavy multiplication sign, removed")},
                        {QStringLiteral("➕"), QStringLiteral("plus, add")},
                        {QStringLiteral("➖"), QStringLiteral("minus, remove")},
                        {QStringLiteral("➗"), QStringLiteral("divide")},
                        {QStringLiteral("🔴"), QStringLiteral("red circle")},
                        {QStringLiteral("🟠"), QStringLiteral("orange circle")},
                        {QStringLiteral("🟡"), QStringLiteral("yellow circle")},
                        {QStringLiteral("🟢"), QStringLiteral("green circle")},
                        {QStringLiteral("🔵"), QStringLiteral("blue circle")},
                        {QStringLiteral("🟣"), QStringLiteral("purple circle")},
                        {QStringLiteral("⚫"), QStringLiteral("black circle")},
                        {QStringLiteral("⚪"), QStringLiteral("white circle")},
                        {QStringLiteral("🔺"), QStringLiteral("red triangle pointing up")},
                        {QStringLiteral("🔻"), QStringLiteral("red triangle pointing down")},
                        {QStringLiteral("🔶"), QStringLiteral("orange diamond")},
                        {QStringLiteral("🔷"), QStringLiteral("blue diamond")},
                        {QStringLiteral("⏳"), QStringLiteral("hourglass, waiting, pending")},
                        {QStringLiteral("⏰"), QStringLiteral("alarm clock, deadline")},
                        {QStringLiteral("🔔"), QStringLiteral("bell, notify")},
                        {QStringLiteral("🔕"), QStringLiteral("bell crossed out, muted")},
                        {QStringLiteral("🎓"), QStringLiteral("graduation cap, student, degree")},
                        {QStringLiteral("🏫"), QStringLiteral("school, university, campus")},
                        {QStringLiteral("🏢"), QStringLiteral("office building, company, department")},
                        {QStringLiteral("🏦"), QStringLiteral("bank, branch")},
                        {QStringLiteral("🏥"), QStringLiteral("hospital, clinic")},
                        {QStringLiteral("🛒"), QStringLiteral("shopping cart, order, basket")},
                        {QStringLiteral("💳"), QStringLiteral("credit card, payment")},
                        {QStringLiteral("💰"), QStringLiteral("money bag, price, salary")},
                        {QStringLiteral("🧾"), QStringLiteral("receipt, invoice, bill")},
                        {QStringLiteral("📦"), QStringLiteral("package, shipment, product")},
                        {QStringLiteral("🚗"), QStringLiteral("car, vehicle")},
                        {QStringLiteral("✈️"), QStringLiteral("aeroplane, flight")},
                        {QStringLiteral("💾"), QStringLiteral("floppy disk, save")},
                        {QStringLiteral("💿"), QStringLiteral("optical disc")},
                        {QStringLiteral("🖥️"), QStringLiteral("desktop computer, server")},
                        {QStringLiteral("💻"), QStringLiteral("laptop, client")},
                        {QStringLiteral("⌨️"), QStringLiteral("keyboard, input")},
                        {QStringLiteral("🖱️"), QStringLiteral("computer mouse, pointer")},
                        {QStringLiteral("🖨️"), QStringLiteral("printer, report")},
                        {QStringLiteral("📱"), QStringLiteral("mobile phone, app")},
                        {QStringLiteral("🌐"), QStringLiteral("globe, network, web")},
                        {QStringLiteral("🔗"), QStringLiteral("link, reference, foreign key")},
                        {QStringLiteral("⚙️"), QStringLiteral("gear, settings, process")},
                        {QStringLiteral("🔧"), QStringLiteral("spanner, maintenance")},
                        {QStringLiteral("🧰"), QStringLiteral("toolbox, tools")},
                        {QStringLiteral("📡"), QStringLiteral("satellite aerial, transmission")},
                        {QStringLiteral("🔌"), QStringLiteral("plug, connection")},
                        {QStringLiteral("🔋"), QStringLiteral("battery, power")},
                        {QStringLiteral("📝"), QStringLiteral("memo, write, edit")},
                        {QStringLiteral("📋"), QStringLiteral("clipboard, list")},
                        {QStringLiteral("📈"), QStringLiteral("chart going up, growth")},
                        {QStringLiteral("📉"), QStringLiteral("chart going down, decline")},
                        {QStringLiteral("🗂️"), QStringLiteral("card index dividers, categories")},
                        {QStringLiteral("🗃️"), QStringLiteral("card file box, records, table")},
                        {QStringLiteral("🗒️"), QStringLiteral("spiral notepad, notes")},
                        {QStringLiteral("📅"), QStringLiteral("calendar, date")},
                        {QStringLiteral("🕐"), QStringLiteral("clock, time")},
                        {QStringLiteral("🏷️"), QStringLiteral("label, tag")},
                        {QStringLiteral("🔖"), QStringLiteral("bookmark")},
                        {QStringLiteral("📑"), QStringLiteral("tabbed documents, index")},
                        {QStringLiteral("📚"), QStringLiteral("books, library")},
                        {QStringLiteral("📖"), QStringLiteral("open book, reference")},
                        {QStringLiteral("➡️"), QStringLiteral("arrow pointing right")},
                        {QStringLiteral("⬅️"), QStringLiteral("arrow pointing left")},
                        {QStringLiteral("⬆️"), QStringLiteral("arrow pointing up")},
                        {QStringLiteral("⬇️"), QStringLiteral("arrow pointing down")},
                        {QStringLiteral("🔄"), QStringLiteral("arrows in a circle, refresh, cycle")},
                        {QStringLiteral("🔀"), QStringLiteral("crossed arrows, shuffle, random")},
                        {QStringLiteral("🔁"), QStringLiteral("repeat, loop")},
                        {QStringLiteral("🔃"), QStringLiteral("vertical arrows, sync")},
                        {QStringLiteral("🌟"), QStringLiteral("glowing star, highlight")},
                        {QStringLiteral("🎯"), QStringLiteral("target, goal")},
                        {QStringLiteral("🏁"), QStringLiteral("chequered flag, finish")},
                        {QStringLiteral("🚀"), QStringLiteral("rocket, launch, release")},
                        {QStringLiteral("🧪"), QStringLiteral("test tube, experiment")},
                        {QStringLiteral("🔬"), QStringLiteral("microscope, analysis")},
                        {QStringLiteral("🍀"), QStringLiteral("clover, luck")},
                        {QStringLiteral("⚡"), QStringLiteral("high voltage, fast")},
                        {QStringLiteral("❄️"), QStringLiteral("snowflake, frozen")},
                        {QStringLiteral("☀️"), QStringLiteral("sun, day")},
                        {QStringLiteral("🌙"), QStringLiteral("moon, night")}}});
        // The people an ERD is usually about. A conceptual diagram's
        // entities are students, employees, patients and customers, and a
        // note about one reads faster with a face on it than without. They
        // are their own group because the emoji drawer is already long, and
        // a search reaches every group anyway.
        all.push_back({QStringLiteral("People"),
                       {{QStringLiteral("🧑"), QStringLiteral("person, user, someone")},
                        {QStringLiteral("👨"), QStringLiteral("man, male")},
                        {QStringLiteral("👩"), QStringLiteral("woman, female")},
                        {QStringLiteral("🧓"), QStringLiteral("older person, elder, senior")},
                        {QStringLiteral("👴"), QStringLiteral("older man, old man, grandfather")},
                        {QStringLiteral("👵"), QStringLiteral("older woman, old woman, grandmother")},
                        {QStringLiteral("🧒"), QStringLiteral("child, kid")},
                        {QStringLiteral("👦"), QStringLiteral("boy")},
                        {QStringLiteral("👧"), QStringLiteral("girl")},
                        {QStringLiteral("👶"), QStringLiteral("baby, infant, newborn")},
                        {QStringLiteral("🤰"), QStringLiteral("pregnant woman, expecting")},
                        {QStringLiteral("🧑‍🍼"), QStringLiteral("person feeding baby, parent")},
                        {QStringLiteral("👤"), QStringLiteral("bust in silhouette, account, single user")},
                        {QStringLiteral("👥"), QStringLiteral("people, group, users")},
                        {QStringLiteral("👪"), QStringLiteral("family, household")},
                        {QStringLiteral("🧑‍🤝‍🧑"), QStringLiteral("people holding hands, pair")},
                        {QStringLiteral("👫"), QStringLiteral("woman and man holding hands, couple")},
                        {QStringLiteral("👬"), QStringLiteral("two men holding hands")},
                        {QStringLiteral("👭"), QStringLiteral("two women holding hands")},
                        {QStringLiteral("🗣️"), QStringLiteral("speaking head, voice, actor")},
                        {QStringLiteral("🧍"), QStringLiteral("person standing, full figure")},
                        {QStringLiteral("🧍‍♂️"), QStringLiteral("man standing, full man")},
                        {QStringLiteral("🧍‍♀️"), QStringLiteral("woman standing, full woman")},
                        {QStringLiteral("🚶"), QStringLiteral("person walking")},
                        {QStringLiteral("🚶‍♂️"), QStringLiteral("man walking")},
                        {QStringLiteral("🚶‍♀️"), QStringLiteral("woman walking")},
                        {QStringLiteral("🏃"), QStringLiteral("person running")},
                        {QStringLiteral("🙋"), QStringLiteral("person raising hand, asking, request")},
                        {QStringLiteral("🧑‍🦽"), QStringLiteral("person in wheelchair, accessibility")},
                        {QStringLiteral("🧑‍🦯"), QStringLiteral("person with white cane, accessibility")},
                        {QStringLiteral("🧑‍🎓"), QStringLiteral("student, learner")},
                        {QStringLiteral("👨‍🎓"), QStringLiteral("man student, male student")},
                        {QStringLiteral("👩‍🎓"), QStringLiteral("woman student, female student")},
                        {QStringLiteral("🧑‍🏫"), QStringLiteral("teacher, instructor, lecturer")},
                        {QStringLiteral("👨‍🏫"), QStringLiteral("man teacher, male teacher")},
                        {QStringLiteral("👩‍🏫"), QStringLiteral("woman teacher, female teacher")},
                        {QStringLiteral("🧑‍⚕️"), QStringLiteral("health worker, doctor, nurse")},
                        {QStringLiteral("👨‍⚕️"), QStringLiteral("man health worker, male doctor")},
                        {QStringLiteral("👩‍⚕️"), QStringLiteral("woman health worker, female doctor")},
                        {QStringLiteral("🧑‍💼"), QStringLiteral("office worker, employee, staff")},
                        {QStringLiteral("👨‍💼"), QStringLiteral("man office worker, male employee")},
                        {QStringLiteral("👩‍💼"), QStringLiteral("woman office worker, female employee")},
                        {QStringLiteral("🧑‍💻"), QStringLiteral("technologist, developer, programmer")},
                        {QStringLiteral("👨‍💻"), QStringLiteral("man technologist, male developer")},
                        {QStringLiteral("👩‍💻"), QStringLiteral("woman technologist, female developer")},
                        {QStringLiteral("🧑‍🔬"), QStringLiteral("scientist, researcher")},
                        {QStringLiteral("👨‍🔬"), QStringLiteral("man scientist, male researcher")},
                        {QStringLiteral("👩‍🔬"), QStringLiteral("woman scientist, female researcher")},
                        {QStringLiteral("🧑‍🌾"), QStringLiteral("farmer, grower")},
                        {QStringLiteral("🧑‍🍳"), QStringLiteral("cook, chef")},
                        {QStringLiteral("🧑‍🏭"), QStringLiteral("factory worker")},
                        {QStringLiteral("🧑‍🔧"), QStringLiteral("mechanic, technician")},
                        {QStringLiteral("🧑‍⚖️"), QStringLiteral("judge, court")},
                        {QStringLiteral("🧑‍✈️"), QStringLiteral("pilot, crew")},
                        {QStringLiteral("🧑‍🚀"), QStringLiteral("astronaut")},
                        {QStringLiteral("🧑‍🎨"), QStringLiteral("artist, designer")},
                        {QStringLiteral("🧑‍🚒"), QStringLiteral("firefighter")},
                        {QStringLiteral("👮"), QStringLiteral("police officer, constable")},
                        {QStringLiteral("👷"), QStringLiteral("construction worker, builder")},
                        {QStringLiteral("💂"), QStringLiteral("guard")},
                        {QStringLiteral("🕵️"), QStringLiteral("detective, investigator")}}});
        return all;
    }();
    return groups;
}

int symbol_group_index(const QString& name) {
    const auto& groups = symbol_groups();
    for (std::size_t index = 0; index < groups.size(); ++index)
        if (groups[index].name.compare(name, Qt::CaseInsensitive) == 0) return static_cast<int>(index);
    return 0;
}

} // namespace erdflow::desktop
